// <auto-generated />
namespace MedicalBilling.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class rmoveProcedreCodeName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rmoveProcedreCodeName));
        
        string IMigrationMetadata.Id
        {
            get { return "202007111351222_rmoveProcedreCodeName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
